---
- name: Start docker domain_exporter container
  community.docker.docker_compose_v2:
    state: present
    project_name: prometheus_domain_exporter
    definition:
      services:
        domain_exporter:
          image: "{{ domain_exporter_docker_image }}:{{ domain_exporter_docker_tag }}"
          container_name: "{{ domain_exporter_container_name }}"
          ports:
            - "127.0.0.1:{{ domain_exporter_host_port }}:{{ domain_exporter_container_port }}"
          hostname: "{{ ansible_host }}"
          restart: always
          labels: "{{ domain_exporter_docker_labels }}"
      networks:
        default:
          external: true
          name: "{{ domain_exporter_docker_network_name }}"
